/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlapifyRouteImport } from './routes/slapify'
import { Route as ReactExeRouteImport } from './routes/react-exe'
import { Route as GhostEnvRouteImport } from './routes/ghost-env'
import { Route as ExecpadRouteImport } from './routes/execpad'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsProductIndexRouteImport } from './routes/docs.$product.index'
import { Route as DocsProductSlugRouteImport } from './routes/docs.$product.$slug'

const SlapifyRoute = SlapifyRouteImport.update({
  id: '/slapify',
  path: '/slapify',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactExeRoute = ReactExeRouteImport.update({
  id: '/react-exe',
  path: '/react-exe',
  getParentRoute: () => rootRouteImport,
} as any)
const GhostEnvRoute = GhostEnvRouteImport.update({
  id: '/ghost-env',
  path: '/ghost-env',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecpadRoute = ExecpadRouteImport.update({
  id: '/execpad',
  path: '/execpad',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsProductIndexRoute = DocsProductIndexRouteImport.update({
  id: '/docs/$product/',
  path: '/docs/$product/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsProductSlugRoute = DocsProductSlugRouteImport.update({
  id: '/docs/$product/$slug',
  path: '/docs/$product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/execpad': typeof ExecpadRoute
  '/ghost-env': typeof GhostEnvRoute
  '/react-exe': typeof ReactExeRoute
  '/slapify': typeof SlapifyRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/$product/$slug': typeof DocsProductSlugRoute
  '/docs/$product/': typeof DocsProductIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/execpad': typeof ExecpadRoute
  '/ghost-env': typeof GhostEnvRoute
  '/react-exe': typeof ReactExeRoute
  '/slapify': typeof SlapifyRoute
  '/docs': typeof DocsIndexRoute
  '/docs/$product/$slug': typeof DocsProductSlugRoute
  '/docs/$product': typeof DocsProductIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/execpad': typeof ExecpadRoute
  '/ghost-env': typeof GhostEnvRoute
  '/react-exe': typeof ReactExeRoute
  '/slapify': typeof SlapifyRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/$product/$slug': typeof DocsProductSlugRoute
  '/docs/$product/': typeof DocsProductIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/execpad'
    | '/ghost-env'
    | '/react-exe'
    | '/slapify'
    | '/docs/'
    | '/docs/$product/$slug'
    | '/docs/$product/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/execpad'
    | '/ghost-env'
    | '/react-exe'
    | '/slapify'
    | '/docs'
    | '/docs/$product/$slug'
    | '/docs/$product'
  id:
    | '__root__'
    | '/'
    | '/execpad'
    | '/ghost-env'
    | '/react-exe'
    | '/slapify'
    | '/docs/'
    | '/docs/$product/$slug'
    | '/docs/$product/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExecpadRoute: typeof ExecpadRoute
  GhostEnvRoute: typeof GhostEnvRoute
  ReactExeRoute: typeof ReactExeRoute
  SlapifyRoute: typeof SlapifyRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsProductSlugRoute: typeof DocsProductSlugRoute
  DocsProductIndexRoute: typeof DocsProductIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slapify': {
      id: '/slapify'
      path: '/slapify'
      fullPath: '/slapify'
      preLoaderRoute: typeof SlapifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react-exe': {
      id: '/react-exe'
      path: '/react-exe'
      fullPath: '/react-exe'
      preLoaderRoute: typeof ReactExeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghost-env': {
      id: '/ghost-env'
      path: '/ghost-env'
      fullPath: '/ghost-env'
      preLoaderRoute: typeof GhostEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execpad': {
      id: '/execpad'
      path: '/execpad'
      fullPath: '/execpad'
      preLoaderRoute: typeof ExecpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$product/': {
      id: '/docs/$product/'
      path: '/docs/$product'
      fullPath: '/docs/$product/'
      preLoaderRoute: typeof DocsProductIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$product/$slug': {
      id: '/docs/$product/$slug'
      path: '/docs/$product/$slug'
      fullPath: '/docs/$product/$slug'
      preLoaderRoute: typeof DocsProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExecpadRoute: ExecpadRoute,
  GhostEnvRoute: GhostEnvRoute,
  ReactExeRoute: ReactExeRoute,
  SlapifyRoute: SlapifyRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsProductSlugRoute: DocsProductSlugRoute,
  DocsProductIndexRoute: DocsProductIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
